---
- name: Deploy DevOps WebApp to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    k8s_manifests_dir: "../k8s"
    deployment_file: "deployment.yaml"
    service_file: "service.yaml"
  
  tasks:
    - name: Ensure kubectl is installed
      command: kubectl version --client
      register: kubectl_version
      changed_when: false
      
    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"
    
    - name: Apply Kubernetes Deployment
      command: kubectl apply -f {{ k8s_manifests_dir }}/{{ deployment_file }}
      register: deployment_result
      
    - name: Display deployment result
      debug:
        msg: "{{ deployment_result.stdout }}"
    
    - name: Apply Kubernetes Service
      command: kubectl apply -f {{ k8s_manifests_dir }}/{{ service_file }}
      register: service_result
      
    - name: Display service result
      debug:
        msg: "{{ service_result.stdout }}"
    
    - name: Wait for deployment to be ready
      command: kubectl rollout status deployment/devops-webapp
      register: rollout_status
      
    - name: Display rollout status
      debug:
        msg: "{{ rollout_status.stdout }}"
    
    - name: Get all pods
      command: kubectl get pods -l app=devops-webapp
      register: pods
      
    - name: Display pods
      debug:
        msg: "{{ pods.stdout }}"
    
    - name: Get service details
      command: kubectl get svc devops-webapp-service
      register: service_info
      
    - name: Display service information
      debug:
        msg: "{{ service_info.stdout }}"